"use client"

export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-white px-4 py-16 md:py-24">
      <div className="max-w-3xl mx-auto">
        {/* Main Heading */}
        <h1 className="text-4xl md:text-5xl font-bold mb-12 pt-20 md:pt-28" style={{ fontFamily: "Playfair Display, serif" }}>
          Terms and Conditions
        </h1>

        {/* Brand Introduction */}
        <p className="text-gray-700 mb-8 leading-relaxed">
          Welcome to Palfrey&گُلابو ("Website"). Palfrey&گُلابو and/or its affiliates provide website features and other
          products and services to you when you visit or shop at our website, use our products or services, or use
          software provided by Palfrey&گُلابو in connection with any of the foregoing.
        </p>

        {/* Section: Acceptance of Terms */}
        <h2 className="text-2xl font-bold mb-4 mt-8" style={{ fontFamily: "Playfair Display, serif" }}>
          Acceptance of Terms
        </h2>
        <p className="text-gray-700 mb-6 leading-relaxed">
          This user agreement ("Terms and Conditions" or "T&C" or "Terms" or "Agreement") is between you ("you" or "End
          User" or "your" or "Buyer" or "Customer" or "Registered User") and Palfrey&گُلابو ("Company" or "us" or "We").
          This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as
          applicable. This electronic record is generated by a computer system and does not require any physical or
          digital signatures.
        </p>
        <p className="text-gray-700 mb-6 leading-relaxed">
          Palfrey&گُلابو is a registered company with business operations involving retail products such as apparel and
          other related goods. The use of the Website is offered to you conditioned on your acceptance of all the terms,
          conditions and notices contained in this User Agreement. Upon acceptance, this User Agreement shall be
          effective and binding upon you along with any amendments made by Palfrey&گُلابو at its sole discretion and
          posted on the Website.
        </p>
        <p className="text-gray-700 mb-6 leading-relaxed">
          Your use of the Website implies that you agree with the terms of the User Agreement. If you do not agree or
          are not willing to be bound by these terms and conditions, please do not click on the "checkbox" and/or on the
          "continue" button and/or "Buy Now" button and do not seek to obtain access to or otherwise use the Website.
        </p>

        {/* Section: Introduction */}
        <h2 className="text-2xl font-bold mb-4 mt-8" style={{ fontFamily: "Playfair Display, serif" }}>
          Introduction
        </h2>
        <p className="text-gray-700 mb-6 leading-relaxed">
          Palfrey&گُلابو is in the business of selling luxury lifestyle retail products such as apparel and other related
          goods. For the purpose of this User Agreement, you as the registered user, guest user, or any natural or legal
          person accessing the Website shall mean any person who is accessing the Website, its contents and using the
          services offered on or through the Website.
        </p>

        {/* Section: Sale & Orders */}
        <h2 className="text-2xl font-bold mb-4 mt-8" style={{ fontFamily: "Playfair Display, serif" }}>
          Sale & Orders
        </h2>
        <p className="text-gray-700 mb-4 leading-relaxed">
          <strong>Please Note:</strong> Palfrey&گُلابو reserves the right to cancel the order at any given point of time.
        </p>
        <ul className="text-gray-700 mb-6 leading-relaxed space-y-3">
          <li className="flex items-start">
            <span className="mr-3">•</span>
            <span>Slight color and fabric variations may happen due to lighting and screen display differences.</span>
          </li>
          <li className="flex items-start">
            <span className="mr-3">•</span>
            <span>Full payment (or advance, if applicable) must be made at the time of placing the order.</span>
          </li>
          <li className="flex items-start">
            <span className="mr-3">•</span>
            <span>Delivery timelines can vary; delays may occur due to courier or logistics issues.</span>
          </li>
          <li className="flex items-start">
            <span className="mr-3">•</span>
            <span>Please double-check your size, measurements and delivery address when placing your order.</span>
          </li>
        </ul>

        {/* Section: Right to Change */}
        <h2 className="text-2xl font-bold mb-4 mt-8" style={{ fontFamily: "Playfair Display, serif" }}>
          Right to Change
        </h2>
        <p className="text-gray-700 mb-6 leading-relaxed">
          Palfrey&گُلابو reserves the sole right to update or modify these Terms and Conditions at any time without prior
          notice. For this reason, we encourage you to review these Terms and Conditions every time you purchase
          products from us or use our Website.
        </p>

        {/* Section: Privacy Policy */}
        <h2 className="text-2xl font-bold mb-4 mt-8" style={{ fontFamily: "Playfair Display, serif" }}>
          Privacy Policy
        </h2>
        <p className="text-gray-700 mb-6 leading-relaxed">
          This privacy policy ("Privacy Policy") shall form an integral part of the Terms of Use of our Website and
          shall be read along with these Terms. Data protection is a matter of trust and your privacy is very important
          to us. We use your personal information only in the manner set out in this Privacy Policy.
        </p>
        <p className="text-gray-700 mb-6 leading-relaxed">
          By visiting this Website you agree to be bound by the terms and conditions of this Privacy Policy. If you do
          not agree, please do not use or access our Website. You have an option to later on withdraw your consent by
          sending an email to our Grievance Officer or through such other electronic address as may be notified to you.
        </p>

        {/* Section: Collection of Personally Identifiable Information */}
        <h2 className="text-2xl font-bold mb-4 mt-8" style={{ fontFamily: "Playfair Display, serif" }}>
          Collection of Personally Identifiable Information
        </h2>
        <p className="text-gray-700 mb-6 leading-relaxed">
          When you use our Website, we collect and store your personal information which is provided by you from time to
          time. Our primary goal in doing so is to provide you a safe, efficient, smooth and customized experience. We
          collect personal information including your email address, name, phone number, credit card/debit card/payment
          instrument details, and browsing behavior.
        </p>
        <p className="text-gray-700 mb-6 leading-relaxed">
          In general, you can browse the Website without telling us who you are or revealing any personal information
          about yourself. Once you give us your personal information, you are not anonymous to us. We automatically
          track certain information about you based upon your behavior on our Website to do internal research on our
          users' demographics, interests, and behavior to better understand, protect and serve our users.
        </p>

        {/* Section: Cookies */}
        <h2 className="text-2xl font-bold mb-4 mt-8" style={{ fontFamily: "Playfair Display, serif" }}>
          Cookies
        </h2>
        <p className="text-gray-700 mb-6 leading-relaxed">
          Cookies are small data files that are placed on your hard drive that assist us in providing our services. We
          use "session" cookies to keep you logged in while you use our Services and to monitor aggregate usage and web
          traffic information. We use "persistent" cookies to recognize you each time you return to our Services.
        </p>
        <p className="text-gray-700 mb-6 leading-relaxed">
          Most internet browsers automatically accept cookies, but you can change your settings or use third-party tools
          to refuse cookies. Please be aware that some parts of our Services may not work for you if you disable
          cookies.
        </p>

        {/* Section: Use of Information */}
        <h2 className="text-2xl font-bold mb-4 mt-8" style={{ fontFamily: "Playfair Display, serif" }}>
          Use of Information
        </h2>
        <p className="text-gray-700 mb-6 leading-relaxed">
          We use personal information to provide the services you request. We do not sell, rent, trade or exchange any
          personally-identifying information of our Users. We may provide your collected information to our affiliates
          and service providers under contract to support the operation of the Website and our services.
        </p>
        <p className="text-gray-700 mb-6 leading-relaxed">
          We use your personal information to resolve disputes, troubleshoot problems, help promote a safe service,
          collect money, measure consumer interest in our products and services, inform you about online and offline
          offers and updates, customize your experience, detect and protect us against fraud and other criminal
          activity, and enforce our terms and conditions.
        </p>

        {/* Section: Sharing of Personal Information */}
        <h2 className="text-2xl font-bold mb-4 mt-8" style={{ fontFamily: "Playfair Display, serif" }}>
          Sharing of Personal Information
        </h2>
        <p className="text-gray-700 mb-6 leading-relaxed">
          We may share personal information with our other corporate entities and affiliates. We may employ third
          parties' services to facilitate aspects of the business, product and service operations that we provide to you
          on the Site. Therefore we may provide some of your personal information to these internal service providers.
          These internal service providers are subject to confidentiality agreements with us.
        </p>
        <p className="text-gray-700 mb-6 leading-relaxed">
          We may disclose personal information if required to do so by law or in the good faith belief that such
          disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal processes. We may
          disclose personal information to law enforcement offices or others in the good faith belief that such
          disclosure is reasonably necessary to enforce our Terms or Privacy Policy.
        </p>

        {/* Section: Security Precautions */}
        <h2 className="text-2xl font-bold mb-4 mt-8" style={{ fontFamily: "Playfair Display, serif" }}>
          Security Precautions
        </h2>
        <p className="text-gray-700 mb-6 leading-relaxed">
          We employ procedural and technological security measures, which are reasonably designed to help protect your
          personal information from unauthorized access or disclosure. We may use encryption, password and physical
          security measures to help protect your personal information against unauthorized access and disclosures.
          However, no security measures are 100% complete.
        </p>
        <p className="text-gray-700 mb-6 leading-relaxed">
          You should take steps to protect against unauthorized access to your password, phone and computer by signing
          off after using a shared computer, choosing a robust password that nobody else knows, and keeping your login
          and password private. Palfrey&گُلابو is not responsible for the unauthorized use of your information or for any
          lost, stolen, compromised passwords.
        </p>

        {/* Section: Choice/Opt-Out */}
        <h2 className="text-2xl font-bold mb-4 mt-8" style={{ fontFamily: "Playfair Display, serif" }}>
          Choice/Opt-Out
        </h2>
        <p className="text-gray-700 mb-6 leading-relaxed">
          You agree and acknowledge that you are providing your Information out of your free will. You have an option
          not to provide or permit us to collect your Personal Information or later on withdraw your consent by sending
          an email to our Grievance Officer or such other electronic address as may be notified to you.
        </p>
        <p className="text-gray-700 mb-6 leading-relaxed">
          You are also under an obligation to use this Website for reasonable and lawful purposes only and shall not
          indulge in any activity that is not envisaged through the Website.
        </p>

        {/* Section: Your Consent */}
        <h2 className="text-2xl font-bold mb-4 mt-8" style={{ fontFamily: "Playfair Display, serif" }}>
          Your Consent
        </h2>
        <p className="text-gray-700 mb-6 leading-relaxed">
          By using the Website and/or by providing your information, you consent to the collection and use of the
          information in accordance with this Privacy Policy. If we decide to change our privacy policy, we will post
          those changes on this page so that you are always aware of what information we collect, how we use it, and
          under what circumstances we disclose it.
        </p>

        {/* Section: Electronic Communications */}
        <h2 className="text-2xl font-bold mb-4 mt-8" style={{ fontFamily: "Playfair Display, serif" }}>
          Electronic Communications
        </h2>
        <p className="text-gray-700 mb-6 leading-relaxed">
          When you use any of our Services or send e-mails to us, you are communicating with us electronically. You
          consent to receive communications from us electronically. We will communicate with you by e-mail or by posting
          notices on this site. You agree that all agreements, notices, disclosures and other communications that we
          provide to you electronically satisfy any legal requirement that such communications be in writing.
        </p>

        {/* Section: Intellectual Property Rights */}
        <h2 className="text-2xl font-bold mb-4 mt-8" style={{ fontFamily: "Playfair Display, serif" }}>
          Intellectual Property Rights
        </h2>
        <p className="text-gray-700 mb-6 leading-relaxed">
          Unless otherwise indicated, Palfrey&گُلابو owns all Intellectual Property Rights to and into the Website,
          including, without limitation, any and all rights, title and interest in copyright, related rights, patents,
          trademarks, trade names, service marks, designs, know-how, trade secrets and inventions. You acknowledge and
          agree that you shall not use, reproduce or distribute any content from the Website belonging to Palfrey&گُلابو
          without obtaining authorization from us.
        </p>
        <p className="text-gray-700 mb-6 leading-relaxed">
          The trademarks, logos and service marks displayed on the Website are the property of Palfrey&گُلابو or their
          vendors or respective third parties. You are not permitted to use these marks without the prior consent of
          Palfrey&گُلابو, the vendor or the third party that may own the marks.
        </p>

        {/* Footer */}
        <div className="border-t border-gray-300 mt-12 pt-8 text-center text-gray-600 text-sm">
          <p>© Palfrey&گُلابو. All rights reserved.</p>
          <p className="mt-2">Last Updated: {new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </div>
  )
}
